site_name: My Docs
theme: 
  name: material
  features:
    - navigation.tabs
    - toc.integration
    - search.suggest
    - navigation.top
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Swith to light mode
      primary: teal
      accent: lime
